"""Analysis endpoints: create analysis, upload images, run OCR.

Phase 9+ — analysis lifecycle with JWT/RBAC protection.
"""

import uuid
from dataclasses import dataclass

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.deps import get_current_user
from app.models.analysis import (
    Analysis,
    AnalysisStatus,
    ImagePosition,
    OCRResult,
    ProductImage,
)
from app.models.user import User, UserRole
from app.schemas.image import OCRResponse, UploadedImageResponse
from app.services import image_service, ocr_service, compliance_service, report_service

router = APIRouter()


def _ensure_not_admin(user: User) -> None:
    """ADMIN may only review the reports generated by LMOs — never run analyses."""
    if user.role.value == "ADMIN":
        raise HTTPException(
            status_code=403,
            detail="Admin cannot perform analyses — only review LMO reports",
        )


def _get_owned_analysis(analysis_id: str, user: User, db: Session) -> Analysis:
    """Return an analysis, enforcing that the user may access it.

    Admin/LMO can view any analysis; other roles can only access their own.
    """
    analysis = db.get(Analysis, analysis_id)
    if analysis is None:
        raise HTTPException(status_code=404, detail="Analysis not found")
    if user.role.value in ("ADMIN", "LMO"):
        return analysis
    if analysis.user_id != user.id:
        raise HTTPException(status_code=403, detail="Not your analysis")
    return analysis


def _analysis_image_paths(db: Session, analysis_id: str) -> list[str]:
    """Return absolute on-disk paths for an analysis's product images.

    Images are stored relative to the working directory; they are resolved to
    absolute paths here so the report generator can embed them in the PDF.
    Missing files are skipped gracefully.
    """
    from pathlib import Path

    images = (
        db.query(ProductImage)
        .filter(ProductImage.analysis_id == analysis_id)
        .order_by(ProductImage.image_position)
        .all()
    )
    paths = []
    for img in images:
        p = Path(img.file_path)
        if not p.is_absolute():
            p = Path.cwd() / p
        if p.exists():
            paths.append(str(p))
    return paths


@router.get(
    "/analyses",
    summary="List analyses visible to the current user",
    tags=["analysis"],
)
def list_analyses(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return analyses the current user is allowed to see.

    - ADMIN: only analyses done by LMO users (transparency into officer work)
    - LMO:   all analyses across every user
    - MANUFACTURER/RETAILER/CONSUMER: only their own analyses
    """
    analyses = db.query(Analysis).order_by(Analysis.created_at.desc())

    if current_user.role.value == "ADMIN":
        # Admin sees the compliance work performed by LMOs only.
        analyses = (
            analyses.join(User, Analysis.user_id == User.id)
            .filter(User.role == UserRole.LMO)
        )
    elif current_user.role.value != "LMO":
        analyses = analyses.filter(Analysis.user_id == current_user.id)

    out = []
    for a in analyses.all():
        owner = a.user
        out.append(
            {
                "id": a.id,
                "status": a.status.value,
                "overall_status": a.overall_status.value if a.overall_status else None,
                "category": a.category,
                "subcategory": a.subcategory,
                "summary": a.summary_json,
                "created_at": a.created_at.isoformat() if a.created_at else None,
                "owner": {
                    "user_id": owner.id if owner else None,
                    "name": owner.full_name if owner else None,
                    "role": owner.role.value if owner else None,
                },
            }
        )
    return out


@router.post(
    "/analyses",
    status_code=201,
    summary="Create a new analysis",
    tags=["analysis"],
)
def create_analysis(
    category: str | None = Form(default=None),
    subcategory: str | None = Form(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create an empty analysis owned by the current authenticated user.

    Images can then be uploaded to this analysis.
    """
    _ensure_not_admin(current_user)
    analysis = Analysis(
        user_id=current_user.id,
        category=category,
        subcategory=subcategory,
        status=AnalysisStatus.PENDING,
    )
    db.add(analysis)
    db.commit()
    db.refresh(analysis)
    return {"analysis_id": analysis.id, "status": analysis.status.value}


@router.post(
    "/analyses/{analysis_id}/images",
    status_code=201,
    summary="Upload a product image to an analysis",
    tags=["analysis"],
)
def upload_image(
    analysis_id: str,
    file: UploadFile = File(...),
    position: str = Form(default="OTHER"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> UploadedImageResponse:
    """Validate and store one image for the analysis.

    Limits: file type, size, decodability are enforced here. The binary is
    stored on disk under uploads/analysis_<id>/; only metadata is persisted.
    """
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    try:
        position_enum = ImagePosition[position.upper()]
    except KeyError:
        valid = [p.name for p in ImagePosition]
        raise HTTPException(
            status_code=422,
            detail=f"Invalid position '{position}'. Valid: {valid}",
        )

    position_lower = position_enum.value.lower()

    data = file.file.read()
    try:
        _, metadata = image_service.save_upload(
            analysis_id=analysis_id,
            data=data,
            position=position_lower,
            original_filename=file.filename or "upload.jpg",
        )
    except image_service.ImageValidationError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    product_image = ProductImage(
        analysis_id=analysis_id,
        filename=metadata["filename"],
        file_path=metadata["saved_path"],
        file_size=metadata["size_bytes"],
        mime_type=metadata["mime_type"],
        image_position=position_enum,
        width=metadata.get("width"),
        height=metadata.get("height"),
    )
    db.add(product_image)
    analysis.status = AnalysisStatus.PROCESSING
    db.commit()
    db.refresh(product_image)

    return UploadedImageResponse(
        analysis_id=analysis_id,
        image={
            "id": product_image.id,
            "filename": product_image.filename,
            "file_path": product_image.file_path,
            "file_size": product_image.file_size,
            "mime_type": product_image.mime_type,
            "image_position": product_image.image_position.value,
            "width": product_image.width,
            "height": product_image.height,
        },
    )


@router.get(
    "/analyses/{analysis_id}/image",
    summary="Serve a product image for an analysis",
    tags=["analysis"],
)
def get_analysis_image(
    analysis_id: str,
    position: str = "FRONT",
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return the stored product image for the requested position.

    Falls back to the first available image (preferring FRONT) if the
    requested position isn't present. Returns the image bytes as-is.
    """
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    try:
        pos_enum = ImagePosition[position.upper()]
    except KeyError:
        valid = [p.name for p in ImagePosition]
        raise HTTPException(
            status_code=422,
            detail=f"Invalid position '{position}'. Valid: {valid}",
        )

    images = db.query(ProductImage).filter(
        ProductImage.analysis_id == analysis_id
    ).all()
    if not images:
        raise HTTPException(status_code=404, detail="No images uploaded")

    # Prefer the requested position; else the first image in a sensible order.
    position_order = {pos.name: i for i, pos in enumerate(ImagePosition)}
    images_sorted = sorted(images, key=lambda i: position_order.get(i.image_position.name, 99))
    selected = next((i for i in images_sorted if i.image_position == pos_enum), images_sorted[0])

    try:
        data = image_service.download_image_bytes(selected.file_path)
    except Exception as exc:
        raise HTTPException(
            status_code=404,
            detail=f"Image could not be retrieved: {exc}",
        )

    from io import BytesIO
    from fastapi.responses import StreamingResponse

    return StreamingResponse(
        BytesIO(data),
        media_type=selected.mime_type or "image/jpeg",
        headers={
            "Content-Disposition": (
                f'inline; filename="{selected.filename}"'
            )
        },
    )


@router.post(
    "/analyses/{analysis_id}/ocr",
    summary="Run OCR on all uploaded images for an analysis",
    tags=["analysis"],
)
def run_ocr(
    analysis_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> dict:
    """Run the OCR pipeline on every image attached to the analysis.

    Returns the combined OCR output. Each image is preprocessed then passed
    to EasyOCR. Raw text, per-block confidence, and bounding boxes are
    persisted as evidence — NOT used to make compliance decisions here.
    """
    _ensure_not_admin(current_user)
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    images = db.query(ProductImage).filter(ProductImage.analysis_id == analysis_id).all()
    if not images:
        raise HTTPException(status_code=400, detail="No images uploaded to this analysis")

    # Reuse the single rebuilt orchestrator (Phase 13) so the duplicated OCR
    # loop no longer lives in the API layer.
    from app.services.analysis.ocr_pipeline import run_pipeline

    out = run_pipeline(analysis, db)

    combined_blocks = []
    combined_text_parts = []
    confidence_sum = 0.0
    count = 0

    for img_group in out.text_blocks:
        for block in img_group["blocks"]:
            combined_blocks.append(
                {
                    "image_id": img_group["image_id"],
                    "position": img_group["position"],
                    "text": block["text"],
                    "confidence": block["confidence"],
                    "bbox": block["bbox"],
                }
            )
        if img_group["raw_text"]:
            combined_text_parts.append(img_group["raw_text"])
        if img_group["confidence"] > 0:
            confidence_sum += img_group["confidence"]
            count += 1

    overall_confidence = round(confidence_sum / count, 4) if count else 0.0

    return {
        "status": out.status,
        "analysis_id": analysis_id,
        "text_blocks": combined_blocks,
        "raw_text": "\n".join(combined_text_parts),
        "confidence": overall_confidence,
        "image_count": len(images),
    }


@router.post(
    "/analyses/{analysis_id}/run",
    summary="Run the complete compliance analysis (OCR → extraction → validation)",
    tags=["analysis"],
)
def run_analysis(
    analysis_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> dict:
    """Orchestrate the full compliance pipeline and return structured results.

    1. Run OCR (reuses already-persisted OCR if present)
    2. Extract structured fields
    3. Classify product
    4. Determine applicable rules (+ exemptions)
    5. Run deterministic rule validators
    6. Aggregate into PASS / FAIL / REVIEW
    7. Persist results
    8. Auto-create an Inspection record so the count updates immediately
    """
    _ensure_not_admin(current_user)
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    result = compliance_service.run_complete_analysis(analysis, db)

    # --- Auto-create Inspection record (BUG A fix) ---
    # The LMO dashboard counts Inspection records.  By creating one here
    # immediately after a successful analysis run, the count updates without
    # requiring the user to manually register a field inspection.
    from app.models import Inspection, InspectionStatus
    from sqlalchemy.orm import Session as _Session

    existing = db.query(Inspection).filter(Inspection.analysis_id == analysis_id).first()
    if existing is None:
        auto = Inspection(
            analysis_id=analysis_id,
            user_id=current_user.id,
            status=InspectionStatus.COMPLETED,
            overall_status=result.get("overall_status"),
            notes="Auto-created after compliance analysis run",
        )
        db.add(auto)
        db.commit()
    else:
        # Update the existing inspection with the latest result
        existing.overall_status = result.get("overall_status")
        if existing.status == InspectionStatus.PENDING:
            existing.status = InspectionStatus.COMPLETED
        db.commit()

    return result


@router.get(
    "/analyses/{analysis_id}/result",
    summary="Get stored analysis results without re-running OCR",
    tags=["analysis"],
)
def get_analysis_result(
    analysis_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return the persisted result of a completed analysis.

    This is a READ-ONLY endpoint. It reconstructs the response from stored
    Analysis + RuleResult + ExtractedField data and never runs OCR. If the
    analysis has not been run yet, returns 409.
    """
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    if analysis.status is None or analysis.status.value != "COMPLETED":
        raise HTTPException(status_code=409, detail="Analysis has no completed result — call POST /run first")

    from app.models.rule import RuleResult, Rule
    from app.models.analysis import ExtractedField

    # Reconstruct rule checks from persisted rule results
    rule_results = (
        db.query(RuleResult, Rule)
        .join(Rule, Rule.id == RuleResult.rule_id)
        .filter(RuleResult.analysis_id == analysis_id)
        .all()
    )

    checks = []
    for rr, rule in rule_results:
        checks.append({
            "rule": rule.rule_number,
            "rule_id": rule.id,
            "title": rule.title,
            "category": rule.category,
            "severity": rule.severity,
            "status": rr.status.value if hasattr(rr.status, 'value') else rr.status,
            "reason": rr.reason or "",
            "evidence": "",
            "confidence": rr.confidence,
        })

    # Reconstruct extracted fields from persisted ExtractedField rows
    extracted_fields = {}
    field_rows = (
        db.query(ExtractedField)
        .filter(ExtractedField.analysis_id == analysis_id)
        .all()
    )
    for fr in field_rows:
        if fr.field_name not in extracted_fields:
            extracted_fields[fr.field_name] = {
                "value": fr.field_value,
                "numeric": fr.field_value_numeric,
                "confidence": fr.confidence,
                "source_text": fr.source_text,
            }

    # Recover raw OCR text from stored OCRResult rows (read-only, no re-run)
    from app.models.analysis import OCRResult
    raw_text = ""
    ocr_rows = (
        db.query(OCRResult)
        .filter(OCRResult.analysis_id == analysis_id)
        .order_by(OCRResult.created_at)
        .all()
    )
    for ocr in ocr_rows:
        if ocr.raw_text:
            raw_text = raw_text + "\n" + ocr.raw_text if raw_text else ocr.raw_text

    # Rebuild compliance score from persisted rule statuses
    from app.compliance.scoring import calculate_score

    @dataclass
    class _FakeCheck:
        rule_number: str
        title: str
        category: str
        severity: str
        status: str
        reason: str
        confidence: float = 0.0

    fake_checks = [
        _FakeCheck(
            rule_number=c["rule"],
            title=c["title"],
            category=c["category"],
            severity=c["severity"],
            status=c["status"],
            reason=c["reason"],
            confidence=c["confidence"],
        )
        for c in checks
    ]
    compliance_score = calculate_score(fake_checks)

    summary = analysis.summary_json or {}
    overall = analysis.overall_status.value if analysis.overall_status else "PENDING"

    return {
        "analysis_id": analysis.id,
        "product": {
            "name": None,
            "category": analysis.category,
            "subcategory": analysis.subcategory or "",
            "classification_confidence": 0.0,
        },
        "overall_status": overall,
        "summary": summary,
        "compliance_score": compliance_score.get_summary(),
        "rules": checks,
        "extracted_fields": extracted_fields,
        "evidence": [],
        "raw_text": raw_text,
    }


@router.get(
    "/analyses/{analysis_id}/report",
    summary="Generate a PDF compliance report",
    tags=["analysis"],
)
def generate_report(
    analysis_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate and return a PDF compliance report for the analysis.

    If the analysis has no results yet, it is not auto-run here; the client
    should call /run first. Returns the PDF file as a download.
    """
    analysis = _get_owned_analysis(analysis_id, current_user, db)

    if analysis.overall_status is None:
        raise HTTPException(
            status_code=400,
            detail="Analysis has no results — call POST /run first",
        )

    # --- Reuse an already-generated PDF if present (no re-analysis) ---
    from app.models import Report
    from pathlib import Path as _Path

    cached_report = (
        db.query(Report)
        .filter(Report.analysis_id == analysis_id)
        .first()
    )
    if cached_report and cached_report.file_path:
        p = _Path(cached_report.file_path)
        if not p.is_absolute():
            p = _Path.cwd() / cached_report.file_path
        if p.exists():
            from fastapi.responses import FileResponse
            return FileResponse(
                path=str(p),
                media_type="application/pdf",
                filename=f"LegalMetriX_Inspection_{analysis_id[:8]}.pdf",
            )

    # Build the data dict from persisted state
    from app.models.rule import RuleResult, Rule
    from dataclasses import dataclass

    rule_results = (
        db.query(RuleResult, Rule)
        .join(Rule, Rule.id == RuleResult.rule_id)
        .filter(RuleResult.analysis_id == analysis_id)
        .all()
    )

    @dataclass
    class _FakeCheck:
        rule_number: str
        title: str
        category: str
        severity: str
        status: str
        reason: str

    checks = [
        _FakeCheck(
            rule_number=rule.rule_number,
            title=rule.title,
            category=rule.category,
            severity=rule.severity,
            status=rr.status,
            reason=rr.reason or "",
        )
        for rr, rule in rule_results
    ]
    check_dicts = [
        {
            "rule": c.rule_number,
            "title": c.title,
            "category": c.category,
            "severity": c.severity,
            "status": c.status,
            "reason": c.reason,
        }
        for c in checks
    ]

    # Calculate compliance score from persisted rule results
    from app.compliance.scoring import calculate_score
    compliance_score = calculate_score(checks)

    summary = analysis.summary_json or {}
    analysis_data = {
        "analysis_id": analysis.id,
        "product": {
            "name": analysis.category or "Unknown",
            "category": f"{analysis.category} / {analysis.subcategory}",
            "subcategory": analysis.subcategory or "",
            "classification_confidence": 0.9,
        },
        "overall_status": analysis.overall_status.value,
        "summary": summary,
        "compliance_score": compliance_score.get_summary(),
        "rules": check_dicts,
        "images": _analysis_image_paths(db, analysis_id),
    }

    generator = report_service.ReportGenerator()
    try:
        report_path = generator.generate(analysis_data, compliance_score)
    except Exception as exc:  # pragma: no cover - report build failure
        raise HTTPException(status_code=500, detail=f"Report generation failed: {exc}")

    from fastapi.responses import FileResponse
    from app.models import Report
    from pathlib import Path as _Path
    import os

    # Persist the generated report so subsequent downloads reuse it (no re-gen).
    if not cached_report:
        try:
            report_size = os.path.getsize(report_path)
        except Exception:
            report_size = None
        db.add(Report(
            analysis_id=analysis.id,
            file_path=str(report_path),
            file_size=report_size,
        ))
        db.commit()

    return FileResponse(
        path=str(report_path),
        media_type="application/pdf",
        filename=f"LegalMetriX_Inspection_{analysis.id[:8]}.pdf",
    )
